spring.application.name=NotificationService

server.port=8086

# Disable Docker Compose support
spring.docker.compose.enabled=false

# Exclude JPA and DataSource auto-configuration (using MongoDB only)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.database=notificationDB

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



# Logging
logging.level.com.Submission.SubmissionService=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
