--
-- PostgreSQL database dump
--

\restrict Fvh6PAhkQChAN1NgyipniS4x6u22veOIPgCgkCe8rKyRVVEqmyurlU8WgJPSU2H

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: public; Owner: ravindra162
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    is_email_verified boolean NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO ravindra162;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: ravindra162
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: ravindra162
--

COPY public.users (id, email, is_email_verified, password, username) FROM stdin;
4	tarakaravindra242005@gmail.com	t	$2a$10$Fi1yBVlr.j8DAB4A0VBImOx6DTQiA75krjtLZlJ774kIk/UCee7M6	ravindra
5	tarakravindra242005@gmail.com	t	$2a$10$303jYlasviYdtX/M04EPYO4TR/S/0KY.I4/RJldeg92M6bFvWFZ1G	ravindra162
6	ravnarravnar@gmail.com	t	$2a$10$2fRKjX2ppMOu62A9Z4o1v.yohmNk4PFtboyCEcHtdiWgSEfdic.Pu	test562
\.


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ravindra162
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: ravindra162
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict Fvh6PAhkQChAN1NgyipniS4x6u22veOIPgCgkCe8rKyRVVEqmyurlU8WgJPSU2H

